### ISSUE TITLE
not able to correctly get height of paint setting view

### ISSUE THREAD

**Issue by zyqu1990** [zhangao0086/DrawingBoard#2]
非常感谢楼主的分享，很有帮助。

我按照你的步骤做下来，在点击画笔设置后，发现PaintingBrushSettingsView的高度一直是0。手工提高弹出高度后，slider不能拉动，想请教一下为什么不能正确获取view的高度？

非常感谢

**Comment by zhangao0086** [comment]
你是说 `systemLayoutSizeFittingSize` 方法处算出来的高度为 0？检查下在 xib 中有没有为 ColorPicker 和 Superview 之间建立Bottom 约束

**Comment by zyqu1990** [comment]
非常感谢回复。后来发现是在xib文件中，对于buttom没有约束。加上之后就一切正常了

2015-06-23 8:06 GMT-07:00 Bannings notifications@github.com:

**Comment by zhangao0086** [comment]
那我就关掉这个 issue 了，如果有其他的问题还请多多反馈 :)

**Comment by zyqu1990** [comment]
好的，这个教程写得真心好

**Comment by zyqu1990** [comment]
我有一个疑问：

如果用图片作为下方 UIBarButtonItem的标示，点击之后，图片会上升至整个toolBar的vertical
center，如果用文字则没有问题一直在底部。

谢谢

在 2015年6月23日 下午6:20，zyqu zyqu1990@gmail.com写道：

> 好的，这个教程写得真心好

**Comment by zhangao0086** [comment]
我随便测了一下，似乎没有发现这个问题：
![1](https://cloud.githubusercontent.com/assets/7742344/8402070/1396f302-1e6a-11e5-97ba-ad8238fd8de7.png)
![2](https://cloud.githubusercontent.com/assets/7742344/8402071/14fa1148-1e6a-11e5-85a1-9b7048f0ef0b.png)

**Comment by zyqu1990** [comment]
可能是因为刷新的那个图标在上升的时候被隐藏了，能否用一个图标替代一下按钮“完成”？

**Comment by zhangao0086** [comment]
我试试

**Comment by zyqu1990** [comment]
后来我还是采用了你的设计，额外增加一个finish editing的状态。这样可以绕过这个问题的。

我查了一下，UITooBar 内部元件都是vertically 居中的，增加自定义个constraint比较麻烦。

**Comment by zhangao0086** [comment]
恩， UIToolBar 会自动为内部元素添加约束的
