### ISSUE TITLE
backgorund image

### ISSUE THREAD

**Issue by mahmoudelfeel** [zhangao0086/DrawingBoard#4]
great app but there is one issue which is when you add an image to the background its not fit do you know how to fix that? 
in the view controller
backgroundsettingvc "function"
self.board.backgroundColor = UIColor(patternImage: Backgroundimage)
you have to implement something called 
CGContextSetPatternPhase
but i dont know how can you help me?

**Comment by zhangao0086** [comment]
Hope this will help you: http://stackoverflow.com/questions/10629403/ios-colorwithpatternimage-stretch-image-full-screen
