### ISSUE TITLE
How to smooth drawn line

### ISSUE THREAD

**Issue by Tachines** [zhangao0086/DrawingBoard#5]
Firstly, thanks for your code, it works well in my device!

But I still found a issue: the line drawn on the canvas is not smooth. So could you please indicate how to smooth each line?

Update:
I solved the smoothing problem by applying auto scale for image rendering. However, it significantly increases CPU load and is very lagging as a result. Please let me know if you have any method to optimise the performance. Thank you!

**Comment by zhangao0086** [comment]
You can try changing it

``` swift
// Board.swift
UIGraphicsBeginImageContext(self.bounds.size)
```

to

``` swift
UIGraphicsBeginImageContextWithOptions(self.bounds.size, NO, UIScreen.mainScreen().scale)
```
